### ISSUE TITLE
Negative temperature not reported?

### ISSUE THREAD

**Issue by msetten** [rthewhite/homebridge-homewizard#4]
I have your plugin successfully running, though I have one issue. I have two thermometers, one indoors one outdoors. The temperature and humidity of the indoors one are correctly reported in various Homekit iOS apps, but for the outdoors one only the humidity is reported correctly, the temperature keeps displaying "Loading..." in one app, or 0.0C in others, even though the correct temperature is -1.2C (which can also be seen on the command line of the homebridge:

Retrieved temperature for: Thermo Buiten its -1.2 degrees
Retrieved humidity for: Thermo Buiten its 89 %

So, as I have tested it with a couple of HomeKit iOS app (like Home, MyHome and iDevices), it seems that somehow your plugin does not transport negative temperatures correctly.

**Comment by rthewhite** [comment]
That's an interesting find! Situation i didn't test, i only have a indoor thermometer. Will look into it, curious to see what's going wrong :+1:

**Comment by rthewhite** [comment]
Fixed, apparently Homebridge and Homekit it's default settings don't allow negative values.
Threw my thermometer in the freezer and now shows negative values correctly :-)

Install the new version:

```
sudo npm update homebridge-homewizard
```

It should give a response on which version was installed, check that it's 0.0.21 to be sure :+1:

**Comment by msetten** [comment]
Dear Raymond,

I don’t know if this reaches you as I am not really familiar with using GitHub, except for downloading packages.

I have created a new type of sensor for your HomeWizard plugin, namely the twilight sensor they sell (which is type=“light” of a parent class called kakusensor as they call it). It does only provide a boolean value whether it is now twilight/night or daylight (light level below or above a certain threshold, but the value itself is not available), so I decided to use the HomeBridge Service: ContactService for it. As I don’t know how to integrate this into GitHub, I just send you the file kakusensor.js and the updated accessories.js

I have also added a lowBattery indicator to the thermometer.js file which is an optional Characteristic in Homebridge/HomeKit. Maybe this is also of use to you. The Kakusensors don’t have this attribute unfortunately.

Feel free to use this all as you see fit.

I would love to also integrate my windmeter and rainwater, but it seems there are no suitable services in HomeBridge. Is this a limitation of HomeBridge or Apple's HomeKit?

Regards,

Mark van Setten

**Comment by rthewhite** [comment]
Hi Mark,

Awesome that you want to contribute. If i understand you correctly you implemented a service for what in Dutch is called a "schemersensor"? Cool!

Was planning on adding the lowBattery indicator as well, so that could save me some work :+1: 

I think it's a limitation from Homekit, the community around Homebridge is quite active so if there was support for it in Homekit it would have been ported to Homebridge as well probably. I looked through the list of available services of Homebridge a while back to see if there was anything else from the HomeWizard to support but couldn't find much.

Sadly enough i don't see your code attached or anything :-( The Github way would be to fork this repo, make your changes, push them to Github and then open a pull request. If you aren't confident to do this you can also mail me the files you changed and i will incorporate them. You can find my personal mail on my profile on Github :+1:
