### ISSUE TITLE
Push sensor changes

### ISSUE THREAD

**Issue by msetten** [rthewhite/homebridge-homewizard#5]
Is there a way that if a sensor value changes, it is automatically pushed to homekit?

Now, if for example a switch is pressed, it doesn't get announced to homekit until I explicitly open up a homekit app which then fetches the values. This also means that triggers that are based on the value of switch are not run until one opens a homekit app, making homekit trigger useless. 

It would be nice if this could be implemented for all types of sensors.

**Comment by rthewhite** [comment]
Sorry for the late reaction, have been very busy last couples of days/weeks. I don't know if this is supported by Homebridge, will have a quick look tonight to see if it's possible and if so how much work it would be.

**Comment by rthewhite** [comment]
I looked in to it, looks like homebridge has some support for it. There appears to be an updateValue characteristic. The only thing is that HomeWizard doesn't support a push mechanisme to update value, so the plugin should then constantly make calls to the HomeWizard to check if the state/value has changed.

Will try to make some time this weekend to see how i can do this nicely. Don't want every accessoiry to constantly fire a stream of requests to the HomeWizard to check it's value.

**Comment by msetten** [comment]
Maybe you could make it configurable? Have a dictionary in the config file for each device that specifies the amount of minutes (or seconds) to retrieve and update the sensor value, with zero meaning to not update it automatically. 

I can see that sensors like thermometers can be updated every 5 to 10 minutes, while something like a door sensor should be updated no less than every minute. 

----
www.markvansetten.com (English)
www.markvansetten.nl (Nederlands)
twitter.com/msetten
facebook.com/msetten
youtube.com/msetten
soundcloud.com/msetten

**Comment by rthewhite** [comment]
Ok i created a working prototype of this today, it pushed the state of a motion sensor to HomeKit. I setup a trigger in Homekit to turn on a light bulb when it saw movement and it worked. Thought of a way to limit the number of requests etc as well. Didn't have a enough time to finish it all up, will try to complete it this week :+1:

**Comment by ygageot** [comment]
Same problem with smoke sensors !

**Comment by rthewhite** [comment]
Yeah it's on my list, been quite busy. Will have another look at it tonight, problem with this is that i need some nice way to handle the interval for the requests. Would like to try and prevent each accessory to have it's on interval running to retrieve things. 

Would like to have one central interval which retrieves the right data and then fires events the accessories listen to and update their value if needed. Since we know the API of the HW isn't really fast need to prevent constant requests being fired.

**Comment by ygageot** [comment]
Something more complex : 
- in the plugin you add a very simple HTTP or UDP server, when it receive any request it ask and refresh the status of all the sensors
- in HW you add an IP Switch "Homebridge" with this request
- in HW you add task/trigger to each important sensor with an action to the IP switch
In addition you can always have a "slow" periodic timer

**Comment by ygageot** [comment]
Do you think that it is possible in api.js when we execute getStatus to loop the accessories/services and fire all the getters ?
If it is possible the advantage is then : when you update one, you update all !

**Comment by ygageot** [comment]
@rthewhite An experience with a contact sensor :
**On HW app **
I added a virtual accessory sending an UDP broadcast message.
I added an action on my contact sensor firing this virtual accessory when changes.
**In the plugin**
I added an UDP server cleaning the caches and sending a special event when it receive something
In contact-sensor.js I added a specific eventListener executing a getContactSensorState
**On Eve app**
I added a scene connected to a lightbulb
I added a trigger with my sensor running these scene

Conclusion, when I open/close my sensor, the plugin execute immediately a getContactSensorState with the fresh value.
BUT the Eve app execute this trigger only if I manually refresh the app.

I am looking for a method to PUSH in HomeKit the new value of the Characteristic.ContactSensorState, some people speaks about **characteristic.updateValue(newValue, null)** but I cannot find it.

Have you some ideas ?

**Comment by rthewhite** [comment]
I did some investigation last night. Looks like the updateValue method is available on the characteristic.
This would mean that we have to change something like this which is now in switch.js:

``` 
service
      .getCharacteristic(this.hap.Characteristic.On)
      .on('set', this.setPowerState.bind(this))
      .on('get', this.getPowerState.bind(this));
```

To:

```
const onCharacteristic = service.getCharateristic(this.hap.Characteristic.On);

onCharacteristic  
      .on('set', this.setPowerState.bind(this))
      .on('get', this.getPowerState.bind(this));

```

onCharacteristic is then supposed to have the updateValue method. Then you need an http server or something which can listen to virtual virtual accessories change. Write some code to call the update method on the correct accessory which will then call the updateValue method of the characteristic. 

That's the global idea, I think running a loop which checks every couple of seconds all accessories won't work with the HomeWizard because of the performance issues. So using the virtual accessory is probably the only reliable way to do this.

Like I said I don't have much time to develop and test it and also don't have a HomeWizard anymore. So if anyone feels up for this, feel free to make a pull request.

**Comment by ygageot** [comment]
I had the time this evening to merge my April tests with the current version and I checked with Home app in place of Eve **and it works** !!! 
_In fact you must execute characteristic.setValue(newValue)._

For the moment I added in HW a unique virtual accessory "HomeKit ping" broadcasting UDP with an OPEN&CLOSE state message.
I added in the plugin a global NotificationListener with inside an UDP server for the moment.
I checked with a contact sensor.
When I open/close the sensor, the Home app widget of the accessory change in less than one second.

For the moment I modified lightly contact-sensor, light-sensor, motion-sensor and smoke-sensor to have the same possibility.

Technically, when the new NotificationListener receive any "ping" , it request all the status from the HW and notify all the HomeKit accessories of any change **immediatly**.

For the moment I made this choice with a unique virtual HW accessory (The reason I named it "Ping")

I dont want to create one virtual for each real.

Probably tomorow I will had in NotificationListener an http server to do the same especially if the plugin is not on the same network but the user must know the IP address of the plugin server... I will lead UPD **and** HTTP in //

**Comment by ygageot** [comment]
@rthewhite 
Do yo want I change the README and version number of the last version ?

**Comment by rthewhite** [comment]
That would be great 👍

**Comment by ygageot** [comment]
In the last version I am thinking about the feature to have  **by default** a periodic refresh with **5** minutes.
Want do you think about that ?

**Comment by rthewhite** [comment]
If you have throughly tested this and it works fine. Im ok with that, it's a great feature to have. 

Think it will be good to mention in the readme though that if you want real time updates you will need to use the http/udp method. Because even an 1 minute interval might be to short to detect a doorbell for example.

**Comment by rthewhite** [comment]
Think this is covered for now right 👍

**Comment by arkadicolson** [comment]
@ygageot 
Hi Can you tell me what exactly you filled in in the ip switch in the fields data? I see the request coming in on Homebridge but then nothing happens...
