### ISSUE TITLE
Failed to retrieved accessories from HomeWizard

### ISSUE THREAD

**Issue by pcvdt** [rthewhite/homebridge-homewizard#6]
Hi Raymond,

I get this message after running the homebridge command.

"pi@raspberrypi ~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-homewizard
Registering platform 'homebridge-homewizard.HomeWizard'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
Initializing HomeWizard platform...
Loading 0 accessories...
Failed to retrieve accessories from HomeWizard
pi@raspberrypi ~ $"

Some days before it said 
"...
 Loading 1 platforms...
Initializing HomeWizard platform...
Loading 0 accessories...
Succesfully retrieved accessories from HomeWizard
Failed to retrieve accessories from HomeWizard" 

Still it doesn't load my accessories and Homekit doesn't seem to find the homewizard.

**Comment by rthewhite** [comment]
Ok this probably means the plugin cant communicate with the HomeWizard. Are you sure that the ip address you entered in the config is correct? Do you have any special characters in your password? It's a known issue that if you have any special characters the plugin can't connect because of encoding issues.

Otherwise try to enable debugging in the config and see if that gives more information so i can help you further.
