### ISSUE TITLE
Unable to update to higher version of Node

### ISSUE THREAD

**Issue by JeeAre70** [rthewhite/homebridge-homewizard#76]
I'm unable to update my node version higher than 4.6.0. If I do so then the homewizard plugin no longer works. I need a higher version of node in order to run another homebridge plugin in parallel. 
However I'm reading various reports of users that they are using node version 7.7.0. Anything I can do?

**Comment by rthewhite** [comment]
Figure out what is causing the problem on node 4.6.0, which part of the code is not compatible. What error is being thrown?

I'm not actively supporting this plugin anymore since i don't have a HomeWizard anymore, nor do i use homebridge in my setup any more. But if people pick it up and create a pull request i'll happily merge and release it.
